### PR TITLE
Add setup for 15SP2 quarterly updates

### PR DESCRIPTION
**Pull request by gyr**

### CODE REVIEW

**Comment by coolo** [comment]
are we doing SP1 and SP2 in parallel? If so, I'd prefer if you avoided the duplication and wrote a loop in the .erb

**Comment by admust** [comment]
@coolo  we will not deliver SP1 QU after releasing SP2

**Comment by coolo** [comment]
in this case please replace SP1 with SP2 instead of duplicating

**Comment by admust** [comment]
@gyr  could you make the job run every Thursday at night not Sunday as configured for SP1

**Comment by admust** [comment]
I ran the job and got an error that home:maintenance-installcheck:15-SP2:QR not exist , @gyr  could you check it?
`sed -e 's,home:maintenance-installcheck:15-SP2:QR,SUSE:SLE-15-SP2:Update:QR,' -i *
osc ci -m 'Fix repoid'
osc sr --yes SUSE:SLE-15-SP2:Update:QR -m 'Update Package List'
[script-executor] -------------------------
[script-executor] Script Type: bash
[script-executor] Script written into '/go/pipelines/SLE15.SP2.QR/185ddb6f-4e09-4185-9deb-e55a72b2c35c.sh'.
Traceback (most recent call last):
  File "./pkglistgen.py", line 8, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.8/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/godata/pipelines/SLE15.SP2.QR/scripts/pkglistgen/cli.py", line 77, in do_update_and_solve
    main_repo = target_config['main-repo']
KeyError: 'main-repo'
Server returned an error: HTTP Error 404: Not Found
Error getting meta for project 'home:maintenance-installcheck:15-SP2:QR' package '000product'
Project not found: home:maintenance-installcheck:15-SP2:QR
./185ddb6f-4e09-4185-9deb-e55a72b2c35c.sh: line 4: cd: home:maintenance-installcheck:15-SP2:QR/000product: No such file or directory
sed: couldn't edit abichecker: not a regular file
Error: '/godata/pipelines/SLE15.SP2.QR/scripts' is not an osc package working copy
Current directory looks like git.
Error: "/godata/pipelines/SLE15.SP2.QR/scripts" is not an osc package working copy.
Current directory looks like git.
[script-executor] Script completed with exit code: 1.
[go] Task status: failed, took: 1.543s`

**Comment by coolo** [comment]
that's nothing Gustavo can fix - I created the SP2 project as maintenance-installcheck

**Pull request merged**
