### PR TITLE
Revert "Add salt packages to DVD for Staging tests"

### PR DESCRIPTION
**Pull request by coolo**
Reverts openSUSE/openSUSE-release-tools#1623

### CODE REVIEW

**Comment by nilxam** [comment]
Fine with me. @DimStar77 ?

**Comment by dirkmueller** [comment]
I thought it works with python 3.7? Wasn't there a comment that it works after fixing requirements?

**Comment by DimStar77** [comment]
Only in the combination of removing salt from the staging tests - but this is counter the initiatives that are planned around salt. We would basically break salt 'until further notice'

> I thought it works with python 3.7? Wasn't there a comment that it works after fixing requirements?

@scarabeusiv indeed did mention something like that last week

**Comment by scarabeusiv** [comment]
Well it should work with python 3.7. At least basic operations worked here localy, but the developers set buildrequire to  < 3.7 (i suppose they can revert that) and then we can carry on.

The only major incompatibility was the tornado 5 not being compatible with salt rather than python 3.7 not being compatible.

**Comment by aplanas** [comment]
The salt package from factory have a patch for 3.7 compatibility. Maybe @isbm have more data about the Tornado situation in upstream.

I suggest to remove in Factory the < 3.7 BR and maintain the tornado one, unless there is a temporal patch for Tornado

**Comment by DimStar77** [comment]
There was indeed a Tornado 4.x submitted that support Python 3.7 - so this should make things smoother

**Comment by coolo** [comment]
I see no movement on the < 3.7 front

**Comment by dirkmueller** [comment]
Patches have been submitted, can we get them checked in?

**Comment by DimStar77** [comment]
> Patches have been submitted, can we get them checked in?

Where has the salt submission for it supporting python 3.7 done? I get this sub, we're basically ready for it.

**Comment by scarabeusiv** [comment]
Well I suppose dirk means https://build.opensuse.org/request/show/665721

**Comment by coolo** [comment]
superseded and accepted as https://build.opensuse.org/request/show/666509 - leaves 3 steps more :)

**Comment by DimStar77** [comment]
https://build.opensuse.org/request/show/666637 is the SR en route to TW - so all in order

**Pull request closed without merging**
