### PR TITLE
Update Announcer for Leap 15.2

### PR DESCRIPTION
**Pull request by lkocman**
* Lubos Kocman is Release Manager for Leap since 1.1.2020

### CODE REVIEW

**Comment by lkocman** [comment]
@nilxam could you please review this one? Thank you

**Comment by DimStar77** [comment]
:+1: 

But a few concerns:

* Are you subscribed to opensuse-factory so you can send mails to that list?
* Before you switch the RM sending out emails, I'd think it would be really nice if that new RM announced the switch on the mailing list, so that people are aware of a new person being in charge and not just happen to 'find out' by a different address sending out release announcement mails.

**Comment by nilxam** [comment]
> But a few concerns:
> 
> * Are you subscribed to opensuse-factory so you can send mails to that list?
> * Before you switch the RM sending out emails, I'd think it would be really nice if that new RM announced the switch on the mailing list, so that people are aware of a new person being in charge and not just happen to 'find out' by a different address sending out release announcement mails.

ah, yes, these concerns sounds reasonable.

**Comment by lkocman** [comment]
Let's postpone until there is official announcement set.  Thank you

**Comment by coolo** [comment]
you better also pause the mail pipeline until this was done - to avoid mixed communication

**Comment by lkocman** [comment]
I've discussed this topic and Ludwig had a nice idea of using the opensuse release team email. In this way we can visualize it as a team effort rather than individual.

**Comment by coolo** [comment]
You still need to subscribe it - and please make sure it doesn't get email :)

**Comment by coolo** [comment]
are  we done here? :)

**Comment by lnussel** [comment]
the address is subscribed, go ahead

**Pull request merged**
