### PR TITLE
Begin porting to python3 (osc branch)

### PR DESCRIPTION
**Pull request by coolo**
This is just the start to experiment with the osc3 branch

### CODE REVIEW

**Comment by jberry-suse** [comment]
So there is movement from osc now? Presumably the `python3` branch on `osc` repo?

**Comment by coolo** [comment]
Yes. But it looks like we can't port to python3 branch and keep sane python2 :(

At least I get this:

```
('adi:1', '\x1b[37mreview:', '\x1b[33msle-release-managers\x1b[39m for \x1b[36mpolicycoreutils\x1b[39m[163031]')
('adi:5', '\x1b[35mbuilding')
('adi:6', '\x1b[35mbuilding')
('adi:10', '\x1b[35mbuilding')

**Comment by jberry-suse** [comment]
That is our code and the change from

```python
print "foo" "bar"
```

to

```python
print("foo", "bar")
```

**Comment by jberry-suse** [comment]
Looks like already replaced with string concatenation which should do the trick.

**Comment by coolo** [comment]
I'm using this for quite a while now (using python2), so I think we can accept it as first step :)

**Comment by coolo** [comment]
I stalled the porting btw as the python3 branch also changed the config parser - and that was a bit too much for me to cover

**Pull request merged**
