### PR TITLE
Support 'required' field for packages

### LINKED ISSUE #1844: pkglistgen: Support 'required' package role
For Factory stagings we want uninstallable "important" patterns to stop building Test DVDs. For Leap this is the default by mean of OSRT:Config's pkglistgen-ignore-unresolvable. Leaving it to openQA to detect KDE being uninstallable is a waste of resource

### PR DESCRIPTION
**Pull request by coolo**
Fixes #1844

### CODE REVIEW

**Comment by DimStar77** [comment]
It seems not to work reliably as intended.

```[ 786s] Mar-24 03:56:06 <2> : [W]    patterns-containers-kubic_admin not found on i586```
(but 000package-groups has ```- patterns-containers-kubic_admin: [required,aarch64,x86_64]```

**Comment by coolo** [comment]
hmm, where is that? I never said a combination with archs works :)

**Comment by DimStar77** [comment]
Had this in Staging:D - where your 000package-groups submission was being staged. After identifying the fail, I unselected it to make the rest progress (can add to :O - the 'catch-all-failure Staging)

**Comment by coolo** [comment]
no need

**Comment by coolo** [comment]
the request was more to raise your interest and to see what other packages would be required

**Pull request merged**
