### PR TITLE
Add ALP pipelines for IBS

### PR DESCRIPTION
**Pull request by gyr**

### CODE REVIEW

**Review by Vogtinator — APPROVED** [review]
A case of "Let's see what happens" I guess...

**Comment by gyr** [comment]
That is true for the changes related to Staging, they should remain disable on botmaster until a Staging area is configured for the project on IBS. The reason for submit them is due to it was a request from ALP architects

**Comment by nilxam** [comment]
Is this PR still valid?

**Comment by dirkmueller** [comment]
has conflicts, so I guess it is obsolete, please let us know if you think otherwise and don't hesitate to reopen then.

**Pull request closed without merging**
