### PR TITLE
dashboard: Add Leap 5.2 micro

### PR DESCRIPTION
**Pull request by ggardet**

### CODE REVIEW

**Comment by coolo** [comment]
Can I close this? It's WIP for 3 weeks now

**Comment by ggardet** [comment]
`source` and `published`  are not fetched properly. And I failed to find the reason so far. Any suggestion?

**Comment by coolo** [comment]
I have no idea about Leap Micro

**Comment by ggardet** [comment]
> `source` and `published` are not fetched properly. And I failed to find the reason so far. Any suggestion?
> 
> EDIT:
> 
> * for `published`, I guess this is because `OSRT:ToTestManagerStatus` does not set `published` value.
> * for `source`, it would be  `ProductVersion` which is missing.

`source` is now fixed thansk to updated attributes. `published` should be fixed with next ttm run.
So, it is ready to merge.

**Pull request merged**
