### PR TITLE
metrics: Fetch openqa jobs in influxdb format

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
building the packages is broken, but this is not the problem of this PR :(

**Comment by jberry-suse** [comment]
And preferably name the dashboard similar to others like `OSRT: openQA`: `openqa.json`.

**Comment by coolo** [comment]
I pushed a .json with the changes you mention blindly applied.

**Comment by jberry-suse** [comment]
Since I resolved the CI failure in #1734 the package was updated and I deployed it to metrics.o.o. After restarted `osrt-metrics-telegraf` service the [dashboard](https://metrics.opensuse.org/d/osrt_openqa/osrt-openqa) is populated with initial data.

**Comment by jberry-suse** [comment]
Something that might be beneficial would be to configure the fill mode in grafana to use previous so when zooming in one doesn't get lots of N to 0 jumps over and over.

**Comment by coolo** [comment]
I tried a lot of things with this - and none work :(

previous doesn't work as we don't write real zeros, we stick with ones (or more) and create fake data.

**Comment by coolo** [comment]
If you have other ideas, let me know - but to me it looks like I need to output *every* worker and *every* job group *every* time to be able to use other fill modes.

**Comment by jberry-suse** [comment]
Yeah, if not always outputting previous will not work so well. For access metrics the code aggregating log data keeps track of what it has previous written and ensures to write zeros if not in current data.

**Comment by coolo** [comment]
can't have that with polling routes

**Comment by jberry-suse** [comment]
Wasn't suggesting that.

**Pull request merged**
