### PR TITLE
Handle deletion of packages with _multibuild (#2943)

### PR DESCRIPTION
**Pull request by Vogtinator**
Also consider its multibuild flavors for deletion.

### CODE REVIEW

**Comment by Vogtinator** [comment]
With this, deletion of `rust1.65` is accepted (previously wasn't) while deletion of `webkit2gtk3` is not (previously was).

**Comment by DimStar77** [comment]
> With this, deletion of `rust1.65` is accepted (previously wasn't) while deletion of `webkit2gtk3` is not (previously was).

That sounds like a very welcome and correct change (I assume it would have accepted wk del req because the "" flavor does nothing)

**Comment by Vogtinator** [comment]
> > With this, deletion of `rust1.65` is accepted (previously wasn't) while deletion of `webkit2gtk3` is not (previously was).
> 
> That sounds like a very welcome and correct change (I assume it would have accepted wk del req because the "" flavor does nothing)

Yep!

**Review by DimStar77 — APPROVED** [review]
LGTM

**Pull request merged**
