### PR TITLE
SLSA support

### PR DESCRIPTION
**Pull request by gyr**
Due to SLSA constrains pkglistgen.py cannot run on botmaster using gocd, as it must run on a separate and isolated server the following changes were added:
- create scripts that run pkgelistgen.py emulating the gocd pipelines (RelPkg and Update.000product)
- create systemd services to execute the scripts for multiple SLSA project
- add log support
- create a rpm package that will be used to deploy it on SLSA server

### CODE REVIEW

**Comment by nilxam** [comment]
the test is failed.

**Review by nilxam — APPROVED** [review]
I'm fine with the change. But we might need to wait https://github.com/openSUSE/openSUSE-release-tools/pull/3062 I assuming that, otherwise the packaging test can not be succesful if I understand that right...

**Review by gleidi-suse — APPROVED** [review]
lgtm

**Comment by gyr** [comment]
> I'm fine with the change. But we might need to wait #3062 I assuming that, otherwise the packaging test can not be succesful if I understand that right...

All checks passed now, package built even with #3062 not being merged.

**Comment by DimStar77** [comment]
somebody forgot about RPM 4.19:

```
can't install openSUSE-release-tools-slsa-build-service-20240315.b086253-1.1.noarch:
nothing provides group(osrt-slsa) needed by openSUSE-release-tools-slsa-build-service-20240315.b086253.noarch
nothing provides user(osrt-slsa) needed by openSUSE-release-tools-slsa-build-service-20240315.b086253.noarch
```

either the user is generated properly using sysusers.d or it is at least advertised in the pkg meta
https://en.opensuse.org/openSUSE:Packaging_guidelines#Users_and_Groups

**Pull request merged**
