### PR TITLE
Convert factory-package-news-web.py to python3

### PR DESCRIPTION
**Pull request by ggardet**

### CODE REVIEW

**Comment by coolo** [comment]
If that's your intention, then also change the shebang

**Comment by ggardet** [comment]
> If that's your intention, then also change the shebang

Fixed.

**Comment by coolo** [comment]
@lnussel @DimStar77 I have no idea how and where this is deployed - so I shy away from merging

**Comment by coolo** [comment]
@lnussel @DimStar77 any help?

**Comment by lnussel** [comment]
runs on openqa and doesnt auto deploy. no impact.

**Pull request merged**
