### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by coolo** [comment]
do we need to enable something on the repo to trigger it?

**Comment by okurz** [comment]
You should not need additional settings. But I suggest to first introduce github actions, merge it, check that it works and only then remove the travis CI config as both GHA and travis can run in parallel.

**Comment by coolo** [comment]
travis won't no longer return, so it removed itself

**Comment by coolo** [comment]
Added the github actions file now (just copied Dirk's)

**Comment by okurz** [comment]
> travis won't no longer return, so it removed itself

We are running projects with travis-ci.com (not travis-ci.org) just fine

**Comment by coolo** [comment]
possibly, but if I need to change the setup anyway, I can change to the real thing :)

**Pull request closed without merging**
