### PR TITLE
Dashboard:fix openQA links

### PR DESCRIPTION
**Pull request by ggardet**
Tested locally.

### CODE REVIEW

**Comment by coolo** [comment]
Did you test it by now?

**Comment by ggardet** [comment]
> Did you test it by now?

No, `python3 dashboard/generate.py` fails with:
```
Traceback (most recent call last):
  File "dashboard/generate.py", line 14, in <module>
    from osclib.conf import Config
ModuleNotFoundError: No module named 'osclib'
```

**Comment by coolo** [comment]
`PYTHONPATH=. python3 dashboard/generate.py` - in doubt you can check in gocd config how our tools are called :)

**Comment by coolo** [comment]
BTW: the package is called osclib - it lacks the python3 prefix for some reason

**Comment by coolo** [comment]
(most likely because it's installed in /usr/share/openSUSE-release-tools/osclib)

**Comment by ggardet** [comment]
> `PYTHONPATH=. python3 dashboard/generate.py` - in doubt you can check in gocd config how our tools are called :)

Ok, thanks.
I tested my latest patches and it does work properly.

**Pull request merged**
