### PR TITLE
Support for Dockerfile builds

### PR DESCRIPTION
**Pull request by Vogtinator**
Draft because:

- [x] Needs to be tested
- [x] Repo name wasn't discussed yet

### CODE REVIEW

**Review by dirkmueller — COMMENTED** [review]
LGTM

**Comment by dirkmueller** [comment]
personally if I may start the bikeshedding, I would prefer repository name "containers" over "docker". (for some reason we picked plural for images). and whether its its docker build or podman or buildah or whatever imho shouldn't matter, it is specific to "Dockerfile".

**Comment by Vogtinator** [comment]
> personally if I may start the bikeshedding, I would prefer repository name "containers" over "docker". (for some reason we picked plural for images)

I'm against `containers` for the simple reason that there are other repo types which also build containers, like `images` with kiwi.

> and whether its its docker build or podman or buildah or whatever imho shouldn't matter, it is specific to "Dockerfile".

What matters most for a repo name is what it builds. For `standard` it's `Type: rpm`, for `images` it's `Type: kiwi` and for `docker` it's `Type: docker`. `dockerfile` would also work.

**Comment by dirkmueller** [comment]
we didn't call repository "standard" as "rpm" either, so I'm not sure there should be an alignment between repository name and repository build type (there isn't one in what you quote as examples). 

I'd simply avoid the use of a trademarked name, hence some other word should be used instead.

**Comment by Vogtinator** [comment]
Ping @DimStar77.

**Comment by DimStar77** [comment]
'containers' seems a bit too broad, especially as we already build lxc and .docker containers (based on kiwi) in 'images' (where we also  have appliances - something TTM is splitting up for us again)

So, I somewhat don't like 'containers' as a repo name on oS:F -having it more relevant to docker makes more sense, docker, docks, docker_containers

**Comment by Vogtinator** [comment]
Staging parts work: https://build.opensuse.org/staging_workflows/home:favogt:releasetest

`docker` builds can be based on `images` and vice versa.

TTM testing is next.

**Comment by Vogtinator** [comment]
> Staging parts work: https://build.opensuse.org/staging_workflows/home:favogt:releasetest
> 
> `docker` builds can be based on `images` and vice versa.
> 
> TTM testing is next.

Both release and publish worked. An incomplete list `docker` products triggers an error as expected and without the list the behaviour is unchanged.

**Comment by Vogtinator** [comment]
Forgot to mention, the `check_source.py` change works as well.

**Comment by dirkmueller** [comment]
> 'containers' seems a bit too broad, especially as we already build lxc and .docker containers (based on kiwi) in 'images' (where we also have appliances - something TTM is splitting up for us again)

@DimStar77 well, I need a generic name that doesn't refer to "docker" because thats a trademark, and that says its a Dockerfile build (which could be docker, it could also be built with buildah etc).

"dockerfile" as repository would also work for me, but thats weird (we don't all "standard" repository as "spec" either, so its inconsistent). 

last suggestion "oci_images" ?

**Comment by Vogtinator** [comment]
> > 'containers' seems a bit too broad, especially as we already build lxc and .docker containers (based on kiwi) in 'images' (where we also have appliances - something TTM is splitting up for us again)
> 
> @DimStar77 well, I need a generic name that doesn't refer to "docker" because thats a trademark, and that says its a Dockerfile build (which could be docker, it could also be built with buildah etc).

OBS requires `Type: docker` for those, which is unavoidable. Feel free to file an issue at https://github.com/openSUSE/open-build-service/ to get that renamed if you think this is an issue.

> "dockerfile" as repository would also work for me, but thats weird (we don't all "standard" repository as "spec" either, so its inconsistent).
>
> last suggestion "oci_images" ?

That's actually wrong in two ways: docker tarballs aren't OCI images and kiwi (`images`) can also build OCI images.

**Comment by dirkmueller** [comment]
the "Type: docker" is more hidden I think, so less of an issue imho. I'd be fine with "dockerfile" , you didn't comment on that?

**Comment by Vogtinator** [comment]
> the "Type: docker" is more hidden I think, so less of an issue imho.

Repo names are also not that visible, so I don't really see much difference there.

> I'd be fine with "dockerfile" , you didn't comment on that?

I suggested that myself in https://github.com/openSUSE/openSUSE-release-tools/pull/2494#issuecomment-729916396.

**Comment by DimStar77** [comment]
> > I'd be fine with "dockerfile" , you didn't comment on that?
> 
> I suggested that myself in [#2494 (comment)](https://github.com/openSUSE/openSUSE-release-tools/pull/2494#issuecomment-729916396).

So that seems like 'dockerfile' is the winner everybody can live with?

**Comment by Vogtinator** [comment]
It should be noted that at least podman/buildah is going in the direction of preferring `Containerfile` meanwhile: https://github.com/containers/buildah/pull/1860

OBS doesn't support that so far, but the repo name could be future proof...

**Comment by dirkmueller** [comment]
I'm okay with "containerfile", it solves the "docker" issue which is the part I was mostly concerned about.

**Comment by aginies** [comment]
Any progress? sounds like there is an agreement for "containerfile", we need to move forward, this is currently blocking us. thx.

**Comment by Vogtinator** [comment]
> I'm okay with "containerfile", it solves the "docker" issue which is the part I was mostly concerned about.

For some reason I didn't get a notification for this comment...

I changed the repo name to `containerfile` everywhere and retested adi stagings and ttm, still working fine.

**Comment by Vogtinator** [comment]
[14:00] <DimStar> fvogt: let's break things :)

So: Merge time!

**Pull request merged**
