### PR TITLE
Staging accept: build-disable the images repository

### PR DESCRIPTION
**Pull request by DimStar77**
With the current pipelines, we enable build of the images repository
once everything in /standard is build-succeeded and repo-checker passed.

Let's go the last mile and disable images when we check in the staging.

This should save some OBS build power (not building ISO images before the
stagings are actually ready) and also some openQA (not testing ISO images
before stagings settle)

I can foresee that sometimes an RM would still want to have preliminary
testing done - in which case the images repo can be manually build enabled
(or the pipeline be triggered to go beyond repo-checker, as it likely also
needs a recalculation of the content)

### CODE REVIEW

**Comment by DimStar77** [comment]
did some checkin rounds with this already and it does what I expected

**Comment by coolo** [comment]
I'm afraid the OBS staging dashboard makes staging projects acceptable too quick.

**Comment by coolo** [comment]
See https://github.com/openSUSE/open-build-service/issues/7359#issuecomment-537016476

**Comment by DimStar77** [comment]
I sort of what afraid that this case could happen for a short time. If I get it right, the gap would be:

* /standard has completed
* pipeline accepted the two installcheck: tests (build-success and repo-checker)

While the pkglistgen runs, /images is still disabled

Could we add another expected: test (like the installchecks) that gets confirmed by 'images enabled' in the pipeline?

**Comment by DimStar77** [comment]
> Could we add another expected: test (like the installchecks) that gets confirmed by 'images enabled' in the pipeline?

That would actually also help in case pkglistgen fails and images is not being enabled at all

**Comment by coolo** [comment]
That check would need to be on standard repository though.

**Comment by coolo** [comment]
I did that now #2757 - the check is to be set to required once it's merged

**Pull request closed without merging**
