### PR TITLE
Trigger aarch64 updates jobs

### PR DESCRIPTION
**Pull request by mloviska**
Motivation: [[qe-core] Increase the coverage of test scenarios in Leap Maintainance - Proposal for tests from SLES to be added to leap](https://progress.opensuse.org/issues/113297)

### CODE REVIEW

**Comment by mloviska** [comment]
Not related to this PR, but I have noticed that `OS_TEST_ISSUES` is empty in last schedules of Leap15.4:

https://openqa.opensuse.org/admin/productlog?id=264922
https://openqa.opensuse.org/admin/productlog?id=264910
https://openqa.opensuse.org/admin/productlog?id=264899

Any idea why?

**Comment by foursixnine** [comment]
> Not related to this PR, but I have noticed that OS_TEST_ISSUES is empty in last schedules of Leap15.4:

@mimi1vx, @msmeissn got any hint?

**Review by dirkmueller — APPROVED** [review]
works for me, we hopefully have enough testing resources on aarch64 for this

**Comment by lkocman** [comment]
I did speak to @mloviska and he lacks rights to merge it. So merging on his behalf.

**Pull request merged**
