### PR TITLE
Add state acceptable_by_lawyer

### PR DESCRIPTION
**Pull request by lkocman**
Related to Issue #3149
States are documented here https://github.com/openSUSE/cavil/blob/master/docs/Architecture.md#states

"accetpable" is reviewed by an expert, "acceptable_by_lawyer" reviewed by an actual lawyer

This new state gives us opportnity to handle situation differently in case that review is done by lawyer, vs best effort.

### CODE REVIEW

**Comment by lkocman** [comment]
Who's responsible for the tool. @darix suggested @gyr

**Comment by kraih** [comment]
Quite a few implementation details of the LegalDB database schema are currently leaking into the legal-auto code. Which means even small changes can have very unintended consequences. It would be very helpful to have someone to discuss with how we can improve the situation in the future.

**Review by kraih — APPROVED** [review]
Not too familiar with the code, but this does look like the right solution to me.

**Review by gyr — COMMENTED** [review]
LGTM

**Review by bugfinder — APPROVED** [review]

**Comment by kraih** [comment]
Thanks, looks like it works. https://legaldb.suse.de/reviews/details/412946 -> https://build.suse.de/request/show/343414

**Pull request merged**
