### PR TITLE
Initial pkglistgen bot for Leap16

### PR DESCRIPTION
**Pull request by lkocman**
* For now let's just make sure we can generate ftp-trees
* It's based on the existing LeapMicro pipeline

### CODE REVIEW

**Review by nilxam — CHANGES_REQUESTED** [review]
do we need another file? can't we use https://github.com/openSUSE/openSUSE-release-tools/blob/master/gocd/pkglistgen.opensuse.gocd.yaml.erb

**Comment by nilxam** [comment]
OTOH you need some pkglistgen default attributes to be set for 16.0 otherwise it won't work porperly, you can copy them from https://build.opensuse.org/attribs/openSUSE:Leap:15.5 , see `OSRT:Config`

**Comment by lkocman** [comment]
Initial OSRT config 
https://build.opensuse.org/attribs/openSUSE:Leap:16.0

Varioables taken from SUSE:ALP and substituted with our values from 15.5 as suggested above.

**Review by nilxam — APPROVED** [review]

**Comment by nilxam** [comment]
https://github.com/openSUSE/openSUSE-release-tools/actions/runs/4373395463/jobs/7651517494

**Comment by lkocman** [comment]
> https://github.com/openSUSE/openSUSE-release-tools/actions/runs/4373395463/jobs/7651517494

Fixed

**Pull request merged**
