### PR TITLE
adi: build kiwi images in a /images repository

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Comment by Vogtinator** [comment]
Test in progress: https://build.opensuse.org/request/show/738556

**Comment by DimStar77** [comment]
> https://build.opensuse.org/project/show/openSUSE:Factory:Staging:adi:40

Test looks good - adi:49 was blocked, as the image was unresolvable. Moved docker_auth into adi:49, now all looks good (short of a pending legal review) - but the process gap was closed

**Comment by DimStar77** [comment]
grmbl... I don't see how this PR causes travis to fail

**Comment by nilxam** [comment]
> grmbl... I don't see how this PR causes travis to fail

no, it's not :)

**Pull request merged**
