### PR TITLE
Schedule Leap15.4 maintenance updates

### PR DESCRIPTION
**Pull request by mloviska**

### CODE REVIEW

**Comment by foursixnine** [comment]
@lkocman @msmeissn

**Comment by msmeissn** [comment]
looks good to me

**Comment by foursixnine** [comment]
@lkocman @okurz who has commit tights to this repo? /cc @coolo

(also, can I haz permissions? :D)

**Comment by okurz** [comment]
I don't have merge permissions, openSUSE RMs have.

@coolo feel welcome to trust more people, like me ;)

**Comment by coolo** [comment]
there are like 80 people with write permissions to this repo.

**Comment by okurz** [comment]
> there are like 80 people with write permissions to this repo.

sure, but only the people *with* the according access know who

**Pull request merged**
