### PR TITLE
do not print coverage to stdout

### PR DESCRIPTION
**Pull request by jreidinger**
First step to make test output a bit more readable.

### CODE REVIEW

**Comment by jreidinger** [comment]
still WIP. I need to check why option is not recognized from https://nose.readthedocs.io/en/latest/plugins/cover.html

**Comment by coolo** [comment]
https://github.com/nose-devs/nose/commit/7c26ad1e6b7d308cafa328ad34736d34028c122a - unreleased since 2016 :)

**Comment by coolo** [comment]
There is a reason https://github.com/openSUSE/openSUSE-release-tools/issues/2524 exists

**Comment by coolo** [comment]
let's close this one

**Pull request closed without merging**
