### PR TITLE
freeze: fix crash when rebasing staging that was earlier enabled by stagingbot

### PR DESCRIPTION
**Pull request by DimStar77**
Fixes issue#2817

### CODE REVIEW

**Comment by DimStar77** [comment]
Regression was apparently introduced with 27c4ae0a0

**Comment by coolo** [comment]
Let's discuss what we want first.
The bug happens if you freeze while the project is building and finished the pipelines before (the images disabled is gone). Leaving the images enabled on a freeze is not necessarily what we want (in #2789 you made a point that freeze is used before selecting new packages).

So what are the chances you want freeze to keep the images repo enabled? And if "always" is the answer, then I'd still favor not to set it to 'enabled' explicitly but rather keep do nothing (i.e. extend the if)

**Comment by DimStar77** [comment]
> Let's discuss what we want first. The bug happens if you freeze while the project is building and finished the pipelines before (the images disabled is gone). Leaving the images enabled on a freeze is not necessarily what we want (in #2789 you made a point that freeze is used before selecting new packages).
> 
> So what are the chances you want freeze to keep the images repo enabled? And if "always" is the answer, then I'd still favor not to set it to 'enabled' explicitly but rather keep do nothing (i.e. extend the if)

I guess 'disable' on freeze is probably always correct, as the next step will be 'building' and then the pipelines re-enabling it.

the only 'error' I can see is if a freeze does not actually change (i.e. freeze, wait until enabled, freeze - but without actually having done any changes to :Factory yet); of course the freeze would be quite non-sense here, but can potentially happen (mostly on 'full rebase of all stagings after prjconf changes like needed for py3.10 switch)

If the 'freeze even if no changes were done' still manages to give us a new repoid and the pipelines passing, then disabling should be the safe bet in all cases.

**Comment by coolo** [comment]
I would say we go with disabled always. If this turns out to be a problem, we can touch the 000release-package on freeze to be sure to get a new repoid.

**Review by coolo — APPROVED** [review]

**Pull request merged**
