### PR TITLE
dist/kubernetes: provide OBS Operator component (and related changes)

### PR DESCRIPTION
**Pull request by jberry-suse**
- 6b02225c75b7c26c2e7d900ce6430d474f7ebdb5:
    dist/kubernetes: utilize new image home in openSUSE:Tools:Images.

- 2e50be7557f80c3c0f60d3efe9b53d1199e73878:
    dist/package: include worker kiwi to allow extraction via _service.
    
    Since the kiwi file will reside in the source package, it needs to be
    referenced in order to appease Factory rpmlint.

- a75f4fbabbaff83ad047973bb7eb1ce0343a7bf1:
    dist/kiwi/worker: include obs-operator subpackage.

- 6b1003fb062aabc542103ee3b91103d18f85d9e4:
    obs_operator: use unbuffered output to work properly in systemd.

- 3ac0086154c85807a56c5be9914ef4caba87bf82:
    dist/kubernetes: provide OBS Operator component.

Should accept [OBS request 649089](https://build.opensuse.org/request/show/649089) after merged to allow for kiwi file to be updated. Created [temporary branched package](https://build.opensuse.org/package/show/openSUSE:Tools:Images/openSUSE-release-tools) in openSUSE:Tools:Images to verify everything works. The package should be re-branched from openSUSE:Tools once merged.

WIP until verify k8s approach with @tampakrap.

### CODE REVIEW

**Comment by jberry-suse** [comment]
Currently deployed and working via this setup, except for final image location which needs to have this merged.

**Comment by coolo** [comment]
So the setup is fixed again - there is nothing to change in k8s though, the image name on registry is the same.

**Comment by jberry-suse** [comment]
The reason I avoided that approach is now kiwi file changes have to be deployed manually. Ideally we could just build the image in the same project as package. The whole setup is rather cumbersome, but that seems to be the rule not the exception.

**Comment by coolo** [comment]
why 'kiwi file changes have to be deployed manually'? What is manual about it?

**Comment by jberry-suse** [comment]
The new package is not updated on merge. Hence changes to kiwi require updating the package manually. Can add that to CI as well.

**Pull request merged**
