### PR TITLE
support committing productcompose files to OBS and not just to git

### PR DESCRIPTION
**Pull request by dcermak**

### CODE REVIEW

**Comment by Vogtinator** [comment]
I guess this fails if there is no 000productcompose in the target project?

**Comment by dcermak** [comment]
Fabian Vogt ***@***.***> writes:

> I guess this fails if there is no 000productcompose in the target project?

Whoops, yes. Should be fixed now

**Comment by dirkmueller** [comment]
@dcermak  needs rebase

**Comment by dcermak** [comment]
This has already been implemented via https://github.com/openSUSE/openSUSE-release-tools/pull/3091

**Pull request closed without merging**
