### PR TITLE
Fix deployment problems on rabbit-openqa

### PR DESCRIPTION
**Pull request by coolo**
- 2 python modules required
- apiurl shouldn't take the default from config not from getopt
- fix typo in user name

### CODE REVIEW

**Comment by coolo** [comment]
ok, let's face it  - the ways OBS can actup are endless. So better leave the restart to systemd :(

```
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/bin/osrt-rabbit-openqa", line 109, in fetch_openqa_jobs
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     http_POST(url, data=xml)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3361, in http_POST
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     def http_POST(*args, **kwargs):   return http_request('POST', *args, **kwargs)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/share/openSUSE-release-tools/osclib/cache.py", line 39, in http_request
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     ret = osc.core._http_request(method, url, headers, data, file)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3349, in http_request
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     fd = urlopen(req, data=data)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     return opener.open(url, data, timeout)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib64/python2.7/urllib2.py", line 429, in open
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     response = self._open(req, data)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     '_open', req)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     result = func(*args)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib/python2.7/site-packages/osc/oscssl.py", line 218, in https_open
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     r = h.getresponse()
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib64/python2.7/httplib.py", line 1121, in getresponse
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     response.begin()
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib64/python2.7/httplib.py", line 438, in begin
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     version, status, reason = self._read_status()
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:   File "/usr/lib64/python2.7/httplib.py", line 402, in _read_status
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]:     raise BadStatusLine(line)
Okt 24 12:59:51 ibs-botmaster osrt-rabbit-openqa[1339]: httplib.BadStatusLine: ''

**Comment by jberry-suse** [comment]
hehe

**Comment by lnussel** [comment]
you are almost there catching potential exceptions :)

**Comment by jberry-suse** [comment]
This causes the following dependency issue on packagelists (SLE-12-SP3). Assume a conditional to use the old name is needed.

```
Problem: nothing provides python2-openqa_client needed by openSUSE-release-tools-totest-manager-20181101.33a4a3b-543.1.noarch
```

**Pull request merged**
