### PR TITLE
metrics: accept more flavors

### PR DESCRIPTION
**Pull request by lnussel**
couldn't test this live, just using a faked setup (#2526)

### CODE REVIEW

**Comment by lnussel** [comment]
actually maybe it makes more sense to accept any value

**Comment by lnussel** [comment]
@coolo what's wrong with the package build here?

**Comment by coolo** [comment]
No idea what OBS was cooking - I deleted the obs project so the bot will recreate it

**Comment by coolo** [comment]
this time it's green

**Comment by lnussel** [comment]
anyone in charge to merge and deploy this?

**Pull request merged**
