### PR TITLE
TTM: Add norelease option for use with OSD

### PR DESCRIPTION
**Pull request by asdil12**
See https://progress.opensuse.org/issues/27735

### CODE REVIEW

**Comment by okurz** [comment]
Uhm, what *is* the difference to "--dry-run" then?

**Comment by asdil12** [comment]
`--dry-run` will not create comments in openQA and also will not save the ignored issues in obs.

**Comment by okurz** [comment]
alright, please add this explanation to the help string of the option then

**Comment by okurz** [comment]
fine :)

**Pull request merged**
