### PR TITLE
gocd: alp-stagings: Re enable Update.000products step for all stagings.

### PR DESCRIPTION
**Pull request by gleidi-suse**
The step is actually required for openQA tests.

### CODE REVIEW

**Review by gyr — DISMISSED** [review]

**Comment by nilxam** [comment]
when https://github.com/openSUSE/openSUSE-release-tools/pull/3024 has merged I'm guessing you may need to re-enable update-000product again unless you want to do a packagelist calculation for each staging per the changes are in the each staging, IOW manual patch 000product per the changes, it's not a terrible thing though if you know what needs add to packagelist and what needs to be drop off from the list.

I don't know what happens in ALP staging but I suppose ALP staging is at a broken state already(except of H), if the default pattern in groups.yml can not be fulfilled then pkglistgen would not give a right list still, but post the wrong bits instead, like add ''FOO is uninstallable: nothing provides BAR'' to packagelist, something like that, just not to update 000product. In fact, if your staging is broken already, you should really fix your staging first: check-in the fix asap, or revert to a working version, make sure the requiring packages are installable. yes, you can workaround groups.yml to get a working packagelist by not adding broken package to packagelist, however you may get a non-working image, and lots of openqa failings. In short, you should fix  your staging first :-)

**Comment by gyr** [comment]
I'm converting this to draft to avoid it be merge by mistake

**Comment by dirkmueller** [comment]
@gyr still needed? can be closed?

**Comment by gyr** [comment]
> @gyr still needed? can be closed?

No, closing it.

**Pull request closed without merging**
